spring:
  application:
    name: SPRING-BOOT-MALL
  profiles:
    active: dev               
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH-mm-ss  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML     
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
        
springdoc:
  swagger-ui:
    path: /swagger-ui
