spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-boot-mall-prod-db
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect      
    open-in-view: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: '587'
    username: ${PROD_MAIL_USERNAME}
    password: ${PROD_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
application:
  host-url: ${PROD_HOST_URL}
  client-url: ${PROD_CLIENT_URL}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}