spring:
  profiles:
    active: dev        
 
  mail:
    host: smtp.gmail.com
    port: '587'
    username: dunz.zheng@gmail.com
    password: tznwurnrrvzhipol
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH-mm-ss
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    
application:
  security:
    jwt:
      secret-key: 5468576D5A7134743677397A24432646294A404E635266556A586E3272357538
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
       
springdoc:
  swagger-ui:
    path: /swagger-ui
