server:
  port: 8080
  

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/mall?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    name: spring-boot-mall-dev-db 
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


application:
  host-url: http://localhost:8080
  client-url: http://localhost:5500
  security:
    jwt:
      secret-key: 5468576D5A7134743677397A24432646294A404E635266556A586E3272357538
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days