server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/mall?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    name: spring-boot-mall-dev-db 
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect 
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: '587'
    username: dunz.zheng@gmail.com
    password: 
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
application:
  host-url: https://d934-27-53-248-234.ngrok-free.app
  client-url: http://127.0.0.1:5500
  call-back-url: http://127.0.0.1:8080/api/callback
  client-back-url: http://127.0.0.1:5500/order.html
  security:
    jwt:
      secret-key: 5468576D5A7134743677397A24432646294A404E635266556A586E3272357538
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days