spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-boot-mall-prod-db
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: '587'
    username: ${PROD_MAIL_USERNAME}
    password: ${PROD_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
application:
  host-url: ${PROD_HOST_URL}
  client-url: ${PROD_CLIENT_URL}
  security:
    jwt:
      secret-key: 5468576D5A7134743677397A24432646294A404E635266556A586E3272357538
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days